### ISSUE TITLE
It doesn't work, what is that.

### ISSUE THREAD

**Issue by Mr-youshuai** [nuxt-modules/style-resources#235]
const isBadge = logObj.badge ?? logObj.level < 2;
  ^
  
  SyntaxError: Invalid or unexpected token
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

   ╭──────────────────────────────────────────────╮
   │                                              │
   │   ✖ Nuxt Fatal Error                         │
   │                                              │
   │   SyntaxError: Invalid or unexpected token   │
   │                                              │

**Comment by Mr-youshuai** [comment]
I use nodev16.13.0. Doesn't the version  support ?

**Comment by manniL** [comment]
Strange, it should have. Maybe another feature - hard to tell without a reproduction.
keep in mind that [Node 18+ is required](https://nuxt.com/docs/getting-started/installation#prerequisites) to run Nuxt based on the docs
